### ISSUE TITLE
SpatialSelectorQueryForm does not catches all errors

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore#368]
If server returns a valid XML with an error message, the plugin hangs on "Quering..."

To reproduce:
1. Break your configuration to output such error
(Hint: create an sql view layer renaming one field to "something with a space in the name")
2. Query that layer with the query tool

**Comment by kappu72** [comment]
This is already closed by https://github.com/geosolutions-it/MapStore/issues/490

**Comment by Gnafu** [comment]
Confirmed to be  already closed by #490
