### ISSUE TITLE
Query Panel generate wrong query in Internet Explorer 11 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore#444]
Query panel sometimes generate a wrong Filter in  Internet Explorer 11. To replicate the problem select a layer and add an equal filter for an attribute, without any spatial filter.
This is because of wrong conversion in OpenLayers filter : see http://osgeo-org.1560.x6.nabble.com/WFS-and-IE-11-td5090636.html

**Comment by Gnafu** [comment]
This specific issue is solved.
All the OpenLayers fixes have been moved in OLFixes.js file.
