### ISSUE TITLE
SpatialSelectorQueryForm  fails autoloading values, if  null value is present in wps values list response

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore#563]
Response: {"values":["Aperto","Chiuso","Chiusura","Chiusura eseguita","Chiusura presa in carico","Sopralluogo eseguito","Sopralluogo preso in carico",null],"featureTypeName":"punti_abbandono","fieldName":"status","size":8}
Error:
Uncaught TypeError: Cannot read property 'value' of null                                                           
(anonymous function)                                                                                                                  
getId                                                                                                                                            
Ext.data.DataReader.extractData                                       
Ext.extend.readRecords
Ext.extend.read                                                        WPSUniqueValuesProxy.js:84 
execOptions.success                                                WPSProcess.js:281
OpenLayers.Request.POST.success                        BaseTypes.js:347
(anonymous function)                                               Request.js:292
OpenLayers.Util.extend.run                                      CallbacksRequest.js:225 request.onreadystatechange                                    XMLHttpRequest.js:333 cXMLHttpRequest.dispatchEvent                             XMLHttpRequest.js:357
fReadyStateChange                                                 XMLHttpRequest.js:214 
_object.onreadystatechange

**Comment by ridethepenguin** [comment]
Hi kappu72,
any hints on how to reproduce the error? I'm experimenting with GeoServer's sample data, topp:states layer (GeoServer version 2.6.2): using QGIS, I set to null the value of attribute STATE_NAME for the Montana state, but instead of getting the exception you reported, I'm simply getting a shorter list of values in the combo (49 values instead of 50).

**Comment by kappu72** [comment]
Hi Stefano,
could you check serever response?
This is what I get
 {"values":["area pianeggiante","area pianegginate","scarpata","zona
valliva",null],"featureTypeName":"punti_abbandono","fieldName":"MORFOLOGIA","size":5}
and becouse of that null value mapstore crash.
This is the error Uncaught TypeError: Cannot read property 'value' of null.
Let me konw.
By kappu

2015-03-16 15:02 GMT+01:00 Stefano Costa <notifications@github.com>:

**Comment by ridethepenguin** [comment]
OK, I managed to reproduce the error... apparently, NULL values in
shapefile data don't cause issues (no null is present in the list returned
by the server), only layers backed by a database (PostGIS in my case) are
affected... weird.

I'll see what I can do to fix the issue.

Thanks,
--S
