### ISSUE TITLE
Manager adds many times same plugin ignoring notDuplicateOutputs:true flag

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore#564]
If plugin configurations has an object as property, tool.js fails to prevent multiple add of same plugin.
When cheking new outputConfig with the previouse one obj==obj return false.

if(this.notDuplicateOutputs
            && this.output.length > 0
            && this.outputTarget){
            for(var i = 0; i < this.output.length; i++){
                if(this.output[i].ownerCt
                    && this.output[i].ownerCt.xtype 
                    && this.output[i].ownerCt.xtype == "tabpanel"
                    && !this.output[i].isDestroyed){
                    var outputConfig = config || this.outputConfig;
                    // Not duplicate tabs
                    for(var index = 0; index < this.output[i].ownerCt.items.items.length; index++){
                        var item = this.output[i].ownerCt.items.items[index];
                        var isCurrentItem = true;
                        for (var key in outputConfig){
                            if(outputConfig[key]){
                                isCurrentItem = isCurrentItem && (outputConfig[key] == item.initialConfig[key]);
                            }
                        }
                        if(isCurrentItem){
                            this.output[i].ownerCt.setActiveTab(index);
                            return;
                        }
                    }
                }
            }
        }

**Comment by ridethepenguin** [comment]
Hi kappu72, could you please provide a sample configuration file? It looks like I can't reproduce the error...

**Comment by kappu72** [comment]
Hi Stefano, try to add this plugin to your configuration.

{

 "ptype": "mxp_servicemanager",

   "buttonText": "Photos",

  "actionTarget":{

             "target": "north.tbar",

             "index": 5

            }

   }

2015-02-25 11:58 GMT+01:00 Stefano Costa <notifications@github.com>:

**Comment by ridethepenguin** [comment]
Thanks, I can see the problem now... I'll write a mail to the devel list
proposing a fix... hold on :-)
