### ISSUE TITLE
FeatureGrid plugin, impossible to export single page in case FeatureManager is WFS_PAGING

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore#595]

**Comment by Gnafu** [comment]
It means that if the FeatureGrid does not have a filter set, the output of the "Single Page" export button is the same of the "All pages" button.
Am I right?

**Comment by kappu72** [comment]
Yes!

2015-03-04 18:44 GMT+01:00 Lorenzo Pini <notifications@github.com>:
