### ISSUE TITLE
Resource Copy

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore#63]
When we copy twice a resource a 'Violate Constraint' exception occurs GeoStore side because the name property is UNIQUE inside the database.

We have to investigate the possibility to add more checks GeoStore side during the save operation (for example returning a specific code to advise the client when a resource already exists) in order to manage this issue.
 See issue [#30](https://github.com/geosolutions-it/geostore/issues/30) on GeoStore

**Comment by ridethepenguin** [comment]
Hi Tobia, I'm trying to fix this issue GeoStore-side: I've added a check on the resource name upon resource creation/update and, in case a resource with the same name is already present in the DB, GeoStore returns an error response with HTTP status 409 and a more meaningful error message (see attached screenshot). Do you think this is enough to consider the issue solved, or you envisage a more sophisticated error handling MapStrore-side (e.g. further error message formatting/localization)?

If you want to take a look at the server-side code, I can make a pull request on the GeoStore project.

![issue63_fixed_err_msg](https://cloud.githubusercontent.com/assets/4783655/5973556/31f5afbc-a86a-11e4-89d4-99d33fcd72b4.png)

**Comment by simboss** [comment]
This discussion should be best placed on the devel list.

**Comment by ridethepenguin** [comment]
OK, I'll repost there. Sorry about that.
