### ISSUE TITLE
Manager - Facebook button always on top

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore#678]
The Facebook "Like" button has recently changed, now it will stay always on top.
To reproduce:
 - Expand a map row from the Manager -> the Facebook button appears
 - Click on "View Map" button

The Map Viewer tab opens but the Facebook button is still visible.
![facebook_badge](https://cloud.githubusercontent.com/assets/3932165/7979575/b099d634-0aa0-11e5-8b2a-29760f09493a.jpg)

**Comment by mbarto** [comment]
Should we make the social network links configurable?

**Comment by Gnafu** [comment]
Not an issue anymore.
Refer to issue #891 to configure social network links
