### ISSUE TITLE
C016 - Improve Styler features

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore#772]
- [ ] Right click on a layer -> Layer Properties -> Styles -> The style editing toolbar appears and quickly disappears. Should the user be able to edit the style in that tab?
- [ ] Styles sections text "Admin styles" and "GeoStore Styles" should be "Public Styles" and "Personal Styles" (Users do not know about GeoStore)
- [ ] Styles dropdowns does not remember the selected style, if the selected style is a personal one (GeoStore Style)
- [ ] Style caching prevents to see changes when selecting a personal style

**Comment by mricca** [comment]
Regarding the first issue the answer is yes. I modified the code. In the layer properties panel the toolbar for editing is hidden and it is only visible in the style editor panel. The unpleasant behavior is no longer present. It is ok?

**Comment by Gnafu** [comment]
So, to clarify, the user will be able to edit the styles only from the "Layer Styles" tool that appears in the toolbar.
If the user navigates to the "Layer Properties" and selects "Styles" tab, he will be able only to select a style for that layer.
