### ISSUE TITLE
Create Chart Options Panel

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore#786]
Create a chart options panel for the query panel for the chart generation (#785).
This panel should a separate widget to inject into the query panel. 
![image](https://cloud.githubusercontent.com/assets/1279510/12778723/9ae9da80-ca64-11e5-8f65-9ec9fa624975.png)

**Comment by mricca** [comment]
![chartbuilder](https://cloud.githubusercontent.com/assets/1880571/12894793/2d27f6ce-ce99-11e5-94c8-c1d34a0eae4f.png)

**Comment by offtherailz** [comment]
When you switch to count the "Y Axis" resets. If the field is valid, it should keep the value. 
When you select Pie or gauge charts,Lables should change :
 * "X Axis" should become a more clear "Group By"
 * "Y Axis" should become "value".
