### ISSUE TITLE
Fail to open WMS with 301 redirection

### ISSUE THREAD

**Issue by robsgnao** [geosolutions-it/MapStore#825]
MapStore cannot open a WMS where a permanent redirection is performed (HTTP code 301); e.g. http://emis.jrc.ec.europa.eu/webservices/4km/wms/modisa?dataset=aph .
Error returned: The WMS Capabilities cannot be added due to problems server side - Invalid capabilities document.

**Comment by offtherailz** [comment]
This issue is caused by this problem in the proxy. https://github.com/geosolutions-it/http-proxy/issues/35
The HTTP code 301 is not manged by the proxy.
