### ISSUE TITLE
Google background doesn't load

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore#843]
Investigate a reported user story:
Da qualche tempo lo sfondo Google Roadmap non viene caricato e visualizzato da MapStore se prima non si è richiesto almeno una volta lo sfondo Google Hybrid.

**Comment by mricca** [comment]
I can not reproduce the issue. I tried different browsers. I tried to reverse the order of layers and to set as the default each of the backgrounds.

**Comment by Gnafu** [comment]
Confirmed. The backgrounds works as expected.
